/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package barra.de.progresso;

import java.util.Random;

/**
 *
 * @author Luiz Dinani
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCPU = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();
        barraCPU = new javax.swing.JProgressBar();
        barraDisco = new javax.swing.JProgressBar();
        barraMemoria = new javax.swing.JProgressBar();
        lblMaxCPU = new javax.swing.JLabel();
        lblMinCPU = new javax.swing.JLabel();
        lblMaxDisco = new javax.swing.JLabel();
        lblMinDisco = new javax.swing.JLabel();
        lblMaxMemoria = new javax.swing.JLabel();
        lblMinMemoria = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblMedCPU = new javax.swing.JLabel();
        lblMedMemoria = new javax.swing.JLabel();
        lblMedDisco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Monitoramento");
        lblTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblCPU.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCPU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCPU.setText("CPU");
        lblCPU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDisco.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDisco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisco.setText("Disco");
        lblDisco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMemoria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMemoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMemoria.setText("Memória");
        lblMemoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        barraCPU.setValue(75);
        barraCPU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barraCPU.setStringPainted(true);

        barraDisco.setValue(65);
        barraDisco.setStringPainted(true);

        barraMemoria.setValue(80);
        barraMemoria.setStringPainted(true);

        lblMaxCPU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaxCPU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaxCPU.setText("Máximo: 90%");
        lblMaxCPU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMinCPU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMinCPU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMinCPU.setText("Mínimo: 10%");

        lblMaxDisco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaxDisco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMaxDisco.setText("Máximo: 100%");
        lblMaxDisco.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblMinDisco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMinDisco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMinDisco.setText("Mínimo: 20%");
        lblMinDisco.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblMaxMemoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaxMemoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaxMemoria.setText("Máximo: 95%");
        lblMaxMemoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMinMemoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMinMemoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMinMemoria.setText("Mínimo: 30%");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Fazer Leitura dos Dados Agora");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblMedCPU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMedCPU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedCPU.setText("Média: 50%");
        lblMedCPU.setFocusable(false);
        lblMedCPU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMedMemoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMedMemoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedMemoria.setText("Média: 62.5%");
        lblMedMemoria.setFocusable(false);
        lblMedMemoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblMedDisco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMedDisco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedDisco.setText("Média: 60%");
        lblMedDisco.setFocusable(false);
        lblMedDisco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(barraCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(212, 212, 212)
                                                .addComponent(lblMaxMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(barraDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(barraMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaxCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblMedCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblMinCPU, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(lblMaxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblMedDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblMinMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblMedMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))))))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPU)
                    .addComponent(lblDisco)
                    .addComponent(lblMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(barraDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(barraCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(barraMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMaxCPU)
                        .addComponent(lblMaxDisco))
                    .addComponent(lblMaxMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedCPU)
                    .addComponent(lblMedMemoria)
                    .addComponent(lblMedDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMinDisco)
                        .addComponent(lblMinMemoria))
                    .addComponent(lblMinCPU, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Random random = new Random();
        //Define novas máximas
        Integer newCPUMax = random.nextInt(101);
        Integer newDiscoMax = random.nextInt(101);
        Integer newMemoriaMax = random.nextInt(101);
        
        //Define novas Mínimas
        Double newCPUMin = newCPUMax*random.nextDouble();
        Double newDiscoMin = newDiscoMax*random.nextDouble();
        Double newMemoriaMin = newMemoriaMax*random.nextDouble();
        
        //Define novas Médias
        Double newCPUMed = (newCPUMax+newCPUMin)/2;
        Double newDiscoMed = (newDiscoMax+newDiscoMin)/2;
        Double newMemoriaMed = (newMemoriaMax+newMemoriaMin)/2;
        
        //Atualizar Máximo nas Labels
        lblMaxCPU.setText(String.format("Máximo: %d%%", newCPUMax));
        lblMaxDisco.setText(String.format("Máximo: %d%%", newDiscoMax));
        lblMaxMemoria.setText(String.format("Máximo: %d%%", newMemoriaMax));
        
        //Atualizar Média nas Labels
        lblMedCPU.setText(String.format("Mínimo: :.2f%%", newCPUMed));
        lblMedDisco.setText(String.format("Mínimo: :.2f%%", newDiscoMed));
        lblMedMemoria.setText(String.format("Mínimo: :.2f%%", newMemoriaMed));
        
        //Atualizar Mínimo nas Labels
        lblMinCPU.setText(String.format("Mínimo: :.2f%%", newCPUMin));
        lblMinDisco.setText(String.format("Mínimo: :.2f%%", newDiscoMin));
        lblMinMemoria.setText(String.format("Mínimo: :.2f%%", newMemoriaMin));

        //Define novos atuais
        Integer newCPUAtual = newCPUMax*(1-random.nextInt());
        Integer newDiscoAtual = newDiscoMax*(1-random.nextInt());
        Integer newMemoriaAtual = newMemoriaMax*(1-random.nextInt());
        
        //Att Valores das Barras
        barraCPU.setValue(newCPUAtual);        
        barraDisco.setValue(newDiscoAtual);
        barraMemoria.setValue(newMemoriaAtual);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraCPU;
    private javax.swing.JProgressBar barraDisco;
    private javax.swing.JProgressBar barraMemoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblMaxCPU;
    private javax.swing.JLabel lblMaxDisco;
    private javax.swing.JLabel lblMaxMemoria;
    private javax.swing.JLabel lblMedCPU;
    private javax.swing.JLabel lblMedDisco;
    private javax.swing.JLabel lblMedMemoria;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblMinCPU;
    private javax.swing.JLabel lblMinDisco;
    private javax.swing.JLabel lblMinMemoria;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
